server {
    listen 80;
    # Remplace par le nom de domaine que tu as configuré sur Cloudflare
    server_name alphanor.org www.alphanor.org; 

    location / {
        proxy_pass http://visir_frontend:4200;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Indispensable pour que le live-reload d'Angular fonctionne via les WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}